modLoader="javafml"
loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]
modId="block_hide_seek"
version="1.0.0"
displayName="Block Hide and Seek"

authors="MoHuia"

description='''一个有趣的方块躲猫猫模组'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.block_hide_seek]] # 这里写主模组的 modId
modId = "map_extra"          # 这里写前置模组的 modId (代码里的那个，不是仓库名)
mandatory = true             # true = 必须安装
versionRange = "[1.0,)"      # 版本范围
ordering = "BEFORE"          # 让前置先加载
side = "BOTH"

